# Site settings
title: Refone Zone
header-img: img/home-bg.jpg
email: hustliuruifeng@gmail.com
copyright_name: Refone
description: "Blog of Refone"

# url: "http://yourdomain.com"
twitter_username: 
github_username:  refone
facebook_username:  刘瑞丰
email_username:  hustliuruifeng@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
